### ISSUE TITLE
请问点击tab，如何触发bar置顶？

### ISSUE THREAD

**Issue by phonegg** [Cornflower1991/RecyclerViewTabLayout#1]
如，运行demo后，点击 “资金往来”分类后，应该滚动到置顶悬浮。

**Comment by phonegg** [comment]
已解决

**Comment by ichapter** [comment]
> 已解决

请问是怎么解决的呢？

**Comment by phonegg** [comment]
> > 已解决
> 
> 请问是怎么解决的呢？

https://github.com/lxfwelldone/Demo_ZFBApp
